ALTER TABLE CHAMPION.LEAGUE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CHAMPION.LEAGUE CASCADE CONSTRAINTS;

CREATE TABLE CHAMPION.LEAGUE
(
  ID          NUMBER,
  NAME        VARCHAR2(100 BYTE),
  START_DATE  DATE,
  STATUS      NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index CHAMPION.SYS_C007808.
--  The object is created when the parent object is created.

ALTER TABLE CHAMPION.LEAGUE ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);
  
  
  ALTER TABLE CHAMPION.MATCHES
 DROP PRIMARY KEY CASCADE;

DROP TABLE CHAMPION.MATCHES CASCADE CONSTRAINTS;

CREATE TABLE CHAMPION.MATCHES
(
  ID                   NUMBER,
  LEAGUE_ID            NUMBER,
  HOME_PARTICIPANT_ID  NUMBER,
  WAY_PARTICIPANT_ID   NUMBER,
  HOME_RESULAT         NUMBER,
  WAY_RESULAT          NUMBER,
  ISWIN                NUMBER,
  START_MATCH          DATE,
  ROUND_NO             NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CHAMPION.MATCHES_PK ON CHAMPION.MATCHES
(ID)
LOGGING
NOPARALLEL;


ALTER TABLE CHAMPION.MATCHES ADD (
  CONSTRAINT MATCHES_PK
  PRIMARY KEY
  (ID)
  USING INDEX CHAMPION.MATCHES_PK
  ENABLE VALIDATE);

ALTER TABLE CHAMPION.PARTICIPANT
 DROP PRIMARY KEY CASCADE;

DROP TABLE CHAMPION.PARTICIPANT CASCADE CONSTRAINTS;

CREATE TABLE CHAMPION.PARTICIPANT
(
  ID      NUMBER,
  NAME    VARCHAR2(100 BYTE),
  EMAIL   VARCHAR2(100 BYTE)                    NOT NULL,
  STATUS  NUMBER                                DEFAULT 0
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index CHAMPION.SYS_C007809.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX CHAMPION.PARTICIPANT_U02 ON CHAMPION.PARTICIPANT
(EMAIL)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CHAMPION.PARTICIPANT_U01 ON CHAMPION.PARTICIPANT
(NAME)
LOGGING
NOPARALLEL;


ALTER TABLE CHAMPION.PARTICIPANT ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT PARTICIPANT_U01
  UNIQUE (NAME)
  USING INDEX CHAMPION.PARTICIPANT_U01
  ENABLE VALIDATE,
  CONSTRAINT PARTICIPANT_U02
  UNIQUE (EMAIL)
  USING INDEX CHAMPION.PARTICIPANT_U02
  ENABLE VALIDATE);


DROP SEQUENCE CHAMPION.LEAGUE_SEQ;

CREATE SEQUENCE CHAMPION.LEAGUE_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE CHAMPION.MATCHES_SEQ;

CREATE SEQUENCE CHAMPION.MATCHES_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE CHAMPION.PARTICIPANT_SEQ;

CREATE SEQUENCE CHAMPION.PARTICIPANT_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


